build:
  version: "2.0"

cards:
  message: "Welcome to ABCBank cards related QA APIs"
  contactDetails:
    name: "Contact us at 1234567890"
    email: "t8P8o@example.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345