build:
  version: "1.0"

accounts:
  message: "Welcome to ABCBank loans related Prod APIs"
  contactDetails:
    name: "Contact us at 1234567890"
    email: "t8P8o@example.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345