spring:
  application:
    name: backend-spring-cloud-config-server
  profiles:
    active: git #Actvie profile defined as git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/LinnLatHtun-MM/ABC_Bank_Config.git"
          default-label: main # Git branch Main
          timeout: 5
          clone-on-start: true #Clone the git repo during the startup of cloud config server
          force-pull: true #if there is any changes on remote repo, force pull during the startup of cloud config server

#http://localhost:8071/encrypt with body t8P8o@example.com
#http://localhost:8071/decrypt with body hfihfnjsdfsbfbh
encrypt:
  key: "0OuDTVWQ13KH3nBGpaA00IoVQ4yhAOJNTRlvFYxE81s="

server:
  port: 8071

  #In a Spring Cloud Config setup, setting the active profile to native tells Spring Cloud Config Server to:
  # 1. Read configuration files from the local file system (or classpath)
  # 2. Read configuration files instead of from a remote Git repository (which is the default).

  # You can call under the following URLs
  #http://localhost:8071/accounts/prod
  #http://localhost:8071/accounts/qa

